name: PEVO Build

on:
  push:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Zig (Estável)
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0

      - name: Compilar PEVO (Compatibilidade Sandy Bridge)
        run: zig build -Doptimize=ReleaseSafe --summary all

      - name: Upload do Executável
        uses: actions/upload-artifact@v4
        with:
          name: pevo-windows-x64
          path: zig-out/bin/pevo.exe
